### ISSUE TITLE
Plugin is not working in IntelliJ 14.1.3

### ISSUE THREAD

**Issue by arkadyes** [ArcBees/gwtp-idea-plugin#62]
I recently upgraded IntelliJ to version 14.1.3 and GWTP plugin to version 1.2.0-beta4. After the upgrade when I try to create a new GWTP project and go through the wizard steps, the project folder is created with .idea subfolder and .iml file. Nothing else. There are no errors in the Event Log.

**Comment by goawash** [comment]
Same happening on Idea 14.0.2 with this version of plugin. Discussion connected to that - https://groups.google.com/forum/#!topic/gwt-platform/_q_EiORgg60

**Comment by olafleur** [comment]
There is a fix in the 1.2.0 branch (which is the main branch). We should release officially a new version of the plugin soon, but you can test in the meantime by downloading it here on GitHub.

**Comment by olafleur** [comment]
Fixed in 1.2.0 release.

**Comment by lynx-r** [comment]
I have this error with IntelliJ Idea 14.1.4:

```
2015-09-18 09:23:57,534 [ 206948]  ERROR - tartup.impl.StartupManagerImpl - null 
java.lang.NullPointerException
    at org.jetbrains.idea.maven.utils.MavenUtil$2.fun(MavenUtil.java:246)
    at org.jetbrains.idea.maven.utils.MavenUtil$2.fun(MavenUtil.java:244)
    at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1735)
    at org.jetbrains.idea.maven.utils.MavenUtil.collectPaths(MavenUtil.java:244)
    at org.jetbrains.idea.maven.project.MavenProjectsManager.initNew(MavenProjectsManager.java:269)
    at org.jetbrains.idea.maven.project.MavenProjectsManager.addManagedFilesWithProfiles(MavenProjectsManager.java:578)
    at org.jetbrains.idea.maven.project.MavenProjectsManager.addManagedFiles(MavenProjectsManager.java:586)
    at com.arcbees.plugin.idea.moduletypes.CreateProjectBuilder.importProject(CreateProjectBuilder.java:123)
    at com.arcbees.plugin.idea.moduletypes.CreateProjectBuilder.moduleCreated(CreateProjectBuilder.java:100)
2015-09-18 09:23:57,541 [ 206955]  ERROR - tartup.impl.StartupManagerImpl - IntelliJ IDEA 14.1.4  Build #IU-141.1532.4 
2015-09-18 09:23:57,541 [ 206955]  ERROR - tartup.impl.StartupManagerImpl - JDK: 1.6.0_65 
2015-09-18 09:23:57,541 [ 206955]  ERROR - tartup.impl.StartupManagerImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-09-18 09:23:57,541 [ 206955]  ERROR - tartup.impl.StartupManagerImpl - Vendor: Apple Inc. 
2015-09-18 09:23:57,542 [ 206956]  ERROR - tartup.impl.StartupManagerImpl - OS: Mac OS X 

```

**Comment by ghost** [comment]
I still have the same issue!
GWTP plugin version is: 1.2.1

below is the relevant part of IDEA's log:
2015-12-26 12:02:03,093 [6494625]   INFO -                  TestNG Runner - Create TestNG Template Configuration 
2015-12-26 12:02:03,141 [6494673]   INFO - ellij.project.impl.ProjectImpl - 200 project components initialized in 67 ms 
2015-12-26 12:02:03,141 [6494673]   INFO - le.impl.ModuleManagerComponent - 0 module(s) loaded in 0 ms 
2015-12-26 12:02:03,144 [6494676]   INFO - i.vcs.changes.ChangeListWorker - default list not found when copy 
2015-12-26 12:02:03,144 [6494676]   INFO - i.vcs.changes.ChangeListWorker - default list not found when copy in original object too 
2015-12-26 12:02:03,515 [6495047]   INFO - tartup.impl.StartupManagerImpl - /Users/armogur/IdeaProjects/Polymer/.idea/misc.xml case-sensitivity: false 
2015-12-26 12:02:03,545 [6495077]   INFO - indexing.UnindexedFilesUpdater - Indexable files iterated in 28 ms 
2015-12-26 12:02:03,569 [6495101]  ERROR - tartup.impl.StartupManagerImpl - null 
java.lang.NullPointerException
    at org.jetbrains.idea.maven.utils.MavenUtil$2.fun(MavenUtil.java:246)
    at org.jetbrains.idea.maven.utils.MavenUtil$2.fun(MavenUtil.java:244)
    at com.intellij.util.containers.ContainerUtil.map(ContainerUtil.java:1735)
    at org.jetbrains.idea.maven.utils.MavenUtil.collectPaths(MavenUtil.java:244)
    at org.jetbrains.idea.maven.project.MavenProjectsManager.initNew(MavenProjectsManager.java:269)
    at org.jetbrains.idea.maven.project.MavenProjectsManager.addManagedFilesWithProfiles(MavenProjectsManager.java:578)
    at org.jetbrains.idea.maven.project.MavenProjectsManager.addManagedFiles(MavenProjectsManager.java:586)
    at com.arcbees.plugin.idea.moduletypes.CreateProjectBuilder.importProject(CreateProjectBuilder.java:123)
    at com.arcbees.plugin.idea.moduletypes.CreateProjectBuilder.moduleCreated(CreateProjectBuilder.java:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
    at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
    at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
    at com.sun.proxy.$Proxy139.moduleCreated(Unknown Source)
    at com.intellij.ide.util.projectWizard.ModuleBuilder.onModuleInitialized(ModuleBuilder.java:279)
    at com.intellij.ide.util.projectWizard.ModuleBuilder.access$000(ModuleBuilder.java:56)
    at com.intellij.ide.util.projectWizard.ModuleBuilder$3$1.run(ModuleBuilder.java:311)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
    at com.intellij.ide.util.projectWizard.ModuleBuilder$3.run(ModuleBuilder.java:308)
    at com.intellij.ide.startup.impl.StartupManagerImpl.b(StartupManagerImpl.java:339)
    at com.intellij.ide.startup.impl.StartupManagerImpl.a(StartupManagerImpl.java:331)
    at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.java:191)
    at com.intellij.openapi.project.impl.ProjectManagerImpl$8$2.run(ProjectManagerImpl.java:496)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2015-12-26 12:02:03,571 [6495103]  ERROR - tartup.impl.StartupManagerImpl - IntelliJ IDEA 14.1.6  Build #IU-141.3056.4 
2015-12-26 12:02:03,572 [6495104]  ERROR - tartup.impl.StartupManagerImpl - JDK: 1.8.0_51 
2015-12-26 12:02:03,572 [6495104]  ERROR - tartup.impl.StartupManagerImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-12-26 12:02:03,572 [6495104]  ERROR - tartup.impl.StartupManagerImpl - Vendor: Oracle Corporation 
2015-12-26 12:02:03,572 [6495104]  ERROR - tartup.impl.StartupManagerImpl - OS: Mac OS X 
2015-12-26 12:02:03,572 [6495104]  ERROR - tartup.impl.StartupManagerImpl - Last Action: CloseProject 
2015-12-26 12:02:03,738 [6495270]   INFO - lij.tasks.impl.TaskManagerImpl - Updating issues cache (every 20 min) 
2015-12-26 12:02:04,201 [6495733]   INFO - tor.impl.FileEditorManagerImpl - Project opening took 1132 ms
